spring:
  application:
    name: gateway-service

  profiles:
    active: $spring.profiles.active$


server:
  port: 8004
  context-path: /

zuul:
  routes:
    api-hello:
      path: /hello-service/**
      serviceId: hello-service
    api-hi:
      path: /hi-service/**
      serviceId: hi-service